---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: nexus3
  name: nexus3
  namespace: devops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nexus3
  template:
    metadata:
      labels:
        k8s-app: nexus3
      namespace: devops
      name: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3:3.20.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: web
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: nexushome
              mountPath: /nexus-data
      volumes:
        - name: nexushome
          hostPath:
            path: /data/devops/nexus3/nexus-data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
 name: nexus3
 namespace: devops
 labels:
   k8s-app: nexus3
spec:
 selector:
   k8s-app: nexus3
 type: NodePort
 ports:
 - name: web
   port: 8081
   targetPort: 8081
   nodePort: 30881
